AskApp/Models/ErrorViewModel.cs
using System;

namespace AskApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AskApp/Models/ThreadDetailsVM.cs
using AskApp.Cross_Cutting.TransferObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AskApp.UI.Models
{
    public class ThreadDetailsVM
    {
        public ThreadTO Thread { get; set; }
        public MessageTO Comment { get; set; }
    }
}

AskApp/Models/ThreadsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AskApp.Cross_Cutting.TransferObjects;

namespace AskApp.UI.Models
{
    public class ThreadsVM
    {
        public List<ThreadTO> Threads { get; set; }
    }
}

AskApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AskApp.Models;

namespace AskApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AskApp/Controllers/ThreadsController.cs
using System;
using AskApp.BLL;
using AskApp.Cross_Cutting.TransferObjects;
using AskApp.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AskApp.UI.Controllers
{
    public class ThreadsController : Controller
    {
        private UserUseCases userRole;

        public ThreadsController()
        {
            userRole = userRole = new UserUseCases();
        }

        // GET: Threads
        public ActionResult Index()
        {
            try
            {
                ThreadsVM threads = new ThreadsVM()
                {
                    Threads = userRole.GetQuestionsByDate()
                };
                return View(threads);
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Threads/Details/5
        public ActionResult Details(int id)
        {
            var thread = userRole.GetByID(id);

            return View(thread);
        }

        // GET: ThreadsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThreadsController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(string title, string body)
        {
            ThreadTO thread = new ThreadTO()
            {
                Question = new MessageTO()
                {
                    Title = title,
                    Body = body
                }
            };
            thread = userRole.CreateThread(thread);
            return RedirectToAction("Details", new { id = thread.Id });
        }

        // GET: ThreadsController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        // PUT: ThreadsController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(int id, string body)
        {
            var thread = userRole.GetByID(id);
            var reply = new MessageTO()
            {
                Body = body
            };
            userRole.Reply(thread, reply);
            return RedirectToAction("Details", new { id = thread.Id });
        }

        // GET: ThreadsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThreadsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AskApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AskApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Threads" asp-action="Index">AskApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threads" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AskApp/Views/Threads/Create.cshtml
@model AskApp.Cross_Cutting.TransferObjects.ThreadTO

<div class="text-left">
    <h4>So, What's bothering you?</h4>

    <form method="post">
        <div class="form-group">
            <label>Title</label>
            <div>
                <input type="text" name="title" />
            </div>
        </div>

        <div class="form-group">
            <label>Body</label>
            <div>
                <textarea class="form-control" type="text" name="body"></textarea>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-success" />
        </div>
    </form>
</div>

AskApp/Views/Threads/Details.cshtml
@model AskApp.Cross_Cutting.TransferObjects.ThreadTO

<div>
    <h4>@Model.Question.Title</h4>
    <p class="font-italic">Posted by @Model.Question.Author.Name on @Model.Question.Date</p>
    <p>@Model.Question.Body</p>

    <div>
        <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#replyForm" aria-expanded="false" aria-controls="collapseExample">
            Reply
        </button>
    </div>

    <div class="collapse" id="replyForm">
        <div class="container border">
            <form method="post">
                <div class="form-group">
                    <label>Write here your reply</label>
                    <div>
                        <textarea class="form-control" type="text" name="body"></textarea>
                    </div>

                    <div class="form-group">
                        <button type="submit" value="Submit" class="btn btn-success" asp-action="Edit" asp-route-Id="@Model.Id"></button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @if (Model.Comments != null)
    {
        foreach (var item in Model.Comments)
        {
            <div class="card card-body"> @item.Body</div>
            <div class="card card-footer"> Posted by @item.Author.Name on @item.Date</div>
        }
    }
</div>

AskApp/Views/Threads/Index.cshtml
@model AskApp.UI.Models.ThreadsVM

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div class="text-left">

        <a asp-controller="Threads" asp-action="Create" class="btn btn-success">Ask Something</a> </p>
    </div>

    @if (Model != null)
    {
        foreach (var item in Model.Threads)
        {
            <div class="card card-header text-left">
                <a asp-controller="Threads" asp-action="Details" asp-route-id="@item.Question.Id">@item.Question.Title</a>
            </div>
            <div class="card-footer">
                <div class="text-left"> Posted by @item.Question.Author.Name On @item.Question.Date</div>
            </div>
        }
    }
</div>